name: VEHICLE_REPOSITION
dependencies:
  - ipykernel
  - numpy
  - pandas
  - "h3-py"
  - ipycytoscape
  - folium
  - matplotlib
  - seaborn
  - scipy
  - "scikit-learn-extra"
  - branca
  - geojson
  - pulp
